# Generated by Django 4.2.4 on 2023-10-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor_users', '0002_rename_editor_users_editorusers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='editorusers',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor_users.editorusers')),
            ],
        ),
    ]
