# Generated by Django 4.2.4 on 2023-10-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_users', '0003_remove_editorusers_id_alter_editorusers_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorusers',
            name='version',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
