# Generated by Django 4.2.4 on 2023-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_users', '0004_editorusers_version_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorusers',
            name='version',
            field=models.IntegerField(),
        ),
    ]
