# Generated by Django 4.2.3 on 2023-10-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor_users', '0008_documenthistory_alter_historydata_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='editor_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='editor_users.editorusers'),
            preserve_default=False,
        ),
    ]
