# Generated by Django 4.2.3 on 2023-10-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_users', '0009_historydata_editor_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydata',
            name='key',
        ),
        migrations.AddField(
            model_name='historydata',
            name='doc_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historydata',
            name='doc_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentHistory',
        ),
    ]
