# Generated by Django 4.2.3 on 2023-10-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_users', '0010_remove_historydata_key_historydata_doc_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historydata',
            old_name='editor_key',
            new_name='key',
        ),
    ]
