# Generated by Django 4.2.3 on 2023-10-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_users', '0011_rename_editor_key_historydata_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydata',
            name='doc_id',
        ),
    ]
